config/routes.rb
Reserver::Application.routes.draw do
  get "release/release_reservation"

  resources :reservations

  resources :reserves

  resources :platforms

  resources :users

root :to => 'reservations#index'  
resources :machines

end

app/models/reservation.rb
class Reservation < ActiveRecord::Base

#attr_accessible :reserve_from, :reserve_to, :reserve_time_from, :reserve_time_to
 
# after_initialize :init


def setnil
self.reserve_from = DateTime.now	
self.reserve_to = DateTime.now
end 

def nilify_attributes!(except = nil)
    except ||= %w{id created_at updated_at}
    attribute_names.reject { |attr| except.include?(attr) }.each { |attr| self[attr] = nil }
  end    

#def init
#      self.reserve_from  ||= 0.0           #will set the default value only if it's nil
#      self.reserve_to ||= build_address #let's you set a default association
#      self.reserve_time_from ||=
#      self.reserve.time_to ||=   
#end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController

 # GET /reservations
  # GET /reservations.json
  def index
    @reservations = Reservation.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @reservations }
    end
  end

  # GET /reservations/1
  # GET /reservations/1.json
  def show
    @reservation = Reservation.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @reservation }
    end
  end

  # GET /reservations/new
  # GET /reservations/new.json
  def new
    @reservation = Reservation.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @reservation }
    end
  end

  # GET /reservations/1/edit
  def edit
    @reservation = Reservation.find(params[:id])
  end

  # POST /reservations
  # POST /reservations.json
  def create
    @reservation = Reservation.new(params[:reservation])

    respond_to do |format|
      if @reservation.save
        format.html { redirect_to @reservation, :notice => 'Reservation was successfully created.' }
        format.json { render :json => @reservation, :status => :created, :location => @reservation }
      else
        format.html { render :action => "new" }
        format.json { render :json => @reservation.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /reservations/1
  # PUT /reservations/1.json
  def update
    @reservation = Reservation.find(params[:id])
    @reservation.reserve_from = Time.now
    @reservation.reserve_to = Time.now	

    respond_to do |format|
      if @reservation.update_attributes(params[:reservation])
        format.html { redirect_to @reservation, :notice => 'Reservation was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @reservation.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /reservations/1
  # DELETE /reservations/1.json
  def destroy
    @reservation = Reservation.find(params[:id])
    @reservation.destroy

    respond_to do |format|
      format.html { redirect_to reservations_url }
      format.json { head :no_content }
    end
  end

def release_reservation
	@reservation = Reservation.find(params[:id])
	@reservation.reserve_to = "2000-01-01"

	respond_to do |format|
	format.html { redirect_to reservations_url, :notice => 'Reservation was successfully released' }
	format.json { head :no_content}
	end
end
end

app/helpers/reservations_helper.rb
module ReservationsHelper



end

app/views/reservations/_form.html.erb
<%= simple_form_for @reservation do |f| %>
  <legend>Make Reservation</legend>
  <%= f.input :machine_name, :collection => Machine.all.collect{|machine| machine.name}, :disabled => true %>
  <%= f.input :machine_platform, :collection => Platform.all.collect{|platform| platform.name}, :disabled => true %>
  <%= f.input :machine_reserver, :collection => User.all.collect{|user| user.name} %>
  <%= f.input :reserve_from, :label => "Reserve Start Date", :as => :datetime %>
  <%#= f.input :reserve_time_from, :label => "Time" -%>
  <%= f.input :reserve_to, :label => "Reservation End Date", :as => :datetime %> 
  <%#= f.input :reserve_time_to, :label => "Time" -%> 
  <% f.input :time_zone, :priority => /US/, :label => "Time Zone" %> 
  <div class="form-actions">
      <%= f.submit 'Make Reservation',:class => 'btn btn-primary' %>
      <%= link_to 'Cancel', reservations_path, :class => 'btn' %>
    </div>
<% end %>	

app/views/reservations/edit.html.erb
<%= render :partial => 'form' %>

app/views/reservations/index.html.erb
<h1>Reservations</h1>
<div id='error'><%= flash[:error]="Message" %></div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th>Machine name</th>
      <th>Platform</th>
      <th>Reserve From</th>    
      <th>Reserve Till</th>
      <th>Reserved By</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @reservations.each do |reservation| %>
      <tr>
        <td><%= reservation.id %></td>
        <td><%= link_to reservation.machine_name, reservation_path(reservation) %></td>
        <td><%= reservation.machine_platform %></td>
	<td>
 <%#= Need to add 'and condition' for time along with date  and use 'Or check nil' -%>	
	<% if (DateTime.now > reservation.reserve_to) %>
	  <%= '-' %> 
	<% else %>
	<%= reservation.reserve_from.to_formatted_s(:long) %>
	<% end %>        
	</td>       

	<td>
	<% if (DateTime.now > reservation.reserve_to) %>
	 <%= '-' %> 
	<% else %>
	<%= reservation.reserve_to.to_formatted_s(:long)  %>
	<% end %>        
	</td>
	
	<td>
	<% if (DateTime.now > reservation.reserve_to) %>
	  <%= '-' %> 
	<% else %>
	<%= reservation.machine_reserver  %>
	<% end %>        
	</td>

	<td>
	<% if (DateTime.now > reservation.reserve_to) %>
	 <%= link_to 'Reserve', edit_reservation_path(reservation), :class => 'btn btn-primary' %> 
	<% else %>
	<b><%= 'Reserved' %></b>
	<td><%= link_to 'Release',reservation_path(reservation), :class => 'btn btn-danger'  %></td>	
 <%#= link_to '(Release)', :controller => "release", :action => "release_reservation", :id => reservation, :confirm => 'Are you sure?', :class => 'btn btn-mini-danger' %>    
	<%#= link_to 'Reserved', reservation_path(reservation), :class => 'btn btn-mini btn-danger' -%> 
	<% end %>
	 <%#= link_to 'Reserve', edit_reservation_path(reservation), :class => 'btn btn-mini' -%>
          
	</td>
      </tr>
    <% end %>
  </tbody>
</table>
<p>Time shown is in 24 Hr format</p>
<%= link_to 'New', new_reservation_path, :class => 'btn btn-primary' %>

app/views/reservations/new.html.erb
<%= render :partial => 'form' %>

app/views/reservations/show.html.erb
<h1>Reservation</h1>
<br>
<p>
  <b>Machine name: </b>
  <%= @reservation.machine_name %>
</p>

<p>
  <b>Machine platform: </b>
  <%= @reservation.machine_platform %>
</p>

<p>
  <b>Reserved by: </b>
  <%= @reservation.machine_reserver %>
</p>

<p>
  <b>Reserve from: </b>
  <%= @reservation.reserve_from.to_formatted_s(:long)  %>
</p>

<p>
  <b>Reserve to: </b>
  <%= @reservation.reserve_to.to_formatted_s(:long)  %>
</p>

<p>
  <b>Reserve status</b><br>
  <%= @reservation.reserve_status %>
</p>

<div class="form-actions">
  <%= link_to 'Back', reservations_path, :class => 'btn'  %>
<%= link_to 'Release', {:controller => "release", :action => "release_reservation", :id => @reservation}, :class => 'btn btn-danger' %>      
<%#= link_to 'Edit', edit_reservation_path(@reservation), :class => 'btn' %>
  <%#= link_to 'Delete', reservation_path(@reservation), :method => 'delete', :confirm => 'Are you sure?', :class => 'btn btn-danger' %>
</div>