config/routes.rb
Reserver::Application.routes.draw do
  get "release/release_reservation"

  resources :reservations

  resources :reserves

  resources :platforms

  resources :users

root :to => 'reservations#index'  
resources :machines

end

app/models/machine.rb
class Machine < ActiveRecord::Base
end

app/controllers/machines_controller.rb
class MachinesController < ApplicationController
  # GET /machines
  # GET /machines.json
  def index
    @machines = Machine.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @machines }
    end
  end

  # GET /machines/1
  # GET /machines/1.json
  def show
    @machine = Machine.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @machine }
    end
  end

  # GET /machines/new
  # GET /machines/new.json
  def new
    @machine = Machine.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @machine }
    end
  end

  # GET /machines/1/edit
  def edit
    @machine = Machine.find(params[:id])
  end

  # POST /machines
  # POST /machines.json
  def create
    @machine = Machine.new(params[:machine])

    respond_to do |format|
      if @machine.save
        format.html { redirect_to @machine, :notice => 'Machine was successfully created.' }
        format.json { render :json => @machine, :status => :created, :location => @machine }
      else
        format.html { render :action => "new" }
        format.json { render :json => @machine.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /machines/1
  # PUT /machines/1.json
  def update
    @machine = Machine.find(params[:id])

    respond_to do |format|
      if @machine.update_attributes(params[:machine])
        format.html { redirect_to @machine, :notice => 'Machine was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @machine.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /machines/1
  # DELETE /machines/1.json
  def destroy
    @machine = Machine.find(params[:id])
    @machine.destroy

    respond_to do |format|
      format.html { redirect_to machines_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/machines_helper.rb
module MachinesHelper
end

app/views/machines/_form.html.erb
<%= simple_form_for @machine do |f| %>
  <legend><%= controller.action_name.capitalize %> Machine</legend>
  <%= f.input :name %>
  <%= f.input :platform,  :collection => ['Linux', 'Mac', 'Windows'], :include_blank => false %>
  <%= f.input :user,  :collection => User.all(:order => 'name') %>
 <div class="form-actions">
     <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to 'Cancel', reservations_path, :class => 'btn' %>
    </div>
<% end %>

app/views/machines/edit.html.erb
<%= render :partial => 'form' %>

app/views/machines/index.html.erb
<h1>Machines</h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Platform</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @machines.each do |machine| %>
      <tr>
        <td><%= machine.id %></td>
        <td><%= link_to machine.name, machine_path(machine) %></td>
        <td><%= machine.platform %></td>
        <td>
          <%= link_to 'Edit', edit_machine_path(machine), :class => 'btn btn-mini' %>
          <%= link_to 'Destroy', machine_path(machine), :method => :delete, :confirm => 'Are you sure?', :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New', new_machine_path, :class => 'btn btn-primary' %>

app/views/machines/new.html.erb
<%= render :partial => 'form' %>

app/views/machines/show.html.erb
<h1>Machine</h1>

<p>
  <b>Name</b><br>
  <%= @machine.name %>
</p>

<p>
  <b>Platform</b><br>
  <%= @machine.platform %>
</p>

<p>
  <b>User</b><br>
  <%= @machine.user %>
</p>

<p>
  <b>Status</b><br>
  <%= @machine.status %>
</p>

<div class="form-actions">
  <%= link_to 'Back', machines_path, :class => 'btn'  %>
  <%= link_to 'Edit', edit_machine_path(@machine), :class => 'btn' %>
  <%= link_to 'Delete', machine_path(@machine), :method => 'delete', :confirm => 'Are you sure?', :class => 'btn btn-danger' %>
</div>