config/routes.rb
Reserver::Application.routes.draw do
  get "release/release_reservation"

  resources :reservations

  resources :reserves

  resources :platforms

  resources :users

root :to => 'reservations#index'  
resources :machines

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Machine Reserver</title>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <a class="brand" href="#">Machine Reserver</a>
        <div class="nav-collapse">
          <ul class="nav">
            <li><%= link_to "Reserve Machines", reservations_path %></li>
	    <li><%= link_to "Browse Machines", machines_path %></li>
            <li><%= link_to "Add machine", new_machine_path %></li>
            <li><%= link_to "Add User", new_user_path %></li>
            <li><%= link_to "List Users", users_path %></li>
            <li><%= link_to "List Platforms", platforms_path %></li>
          </ul>
        </div>
      </div>
    </div>
  </div>

  <div class="container">
    <div class="row">
      <div class="span9"><%= yield %></div>
<!--      <div class="span3">
       <h2>About Us</h2>
        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
      </div> -->
    </div> 
  </div> 
</body>
</html>